// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwdqbobralmeifknavck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3ZHFib2JyYWxtZWlma25hdmNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODY3NTMsImV4cCI6MjA2NjI2Mjc1M30.7DXjo3MxMeNYyePrfxgK0tH6VEFBLK9TmzQp2Y5uzxg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);